feat(ls): provide OpenAPI 3.1.0 completion rules for Responses object
swagger-api/apidom pull request #2196
Opened 2022-10-26 22:56 UTC by tim-lai

### Description

* provide OpenAPI 3.1.0 completion rules for Responses object

### Motivation and Context

Ref: #2062 
Ref: #2061 (no update required)

### How Has This Been Tested?

### Screenshots (if appropriate):

## Checklist

### My PR contains...

- [ ] No code changes (`src/` is unmodified: changes to documentation, CI, metadata, etc.)
- [ ] Dependency changes (any modification to dependencies in `package.json`)
- [ ] Bug fixes (non-breaking change which fixes an issue)
- [ ] Improvements (misc. changes to existing features)
- [x] Features (non-breaking change which adds functionality)

### My changes...
- [ ] are breaking changes to a public API (config options, System API, major UI change, etc).
- [ ] are breaking changes to a private API (Redux, component props, utility functions, etc.).
- [ ] are breaking changes to a developer API (npm script behavior changes, new dev system dependencies, etc).
- [x] are not breaking changes.

### Documentation
- [ ] My changes do not require a change to the project documentation.
- [ ] My changes require a change to the project documentation.
- [ ] If yes to above: I have updated the documentation accordingly.

### Automated tests
- [ ] My changes can not or do not need to be tested.
- [ ] My changes can and should be tested by unit and/or integration tests.
- [ ] If yes to above: I have added tests to cover my changes.
- [ ] If yes to above: I have taken care to cover edge cases in my tests.
- [x] All new and existing tests passed.

2022-10-26 22:59 UTC, tim-lai commented
@char0n I pretty matched the OAS3.0.x version, however, how to best test the response codes? Even without this PR, I'm not getting a suggestion for auto complete in OAS3.0.x definition for `'20...'` (string) or `20...` (number). With partial http code and without closing `:`, I do get the error that `responses` should contain an object.

2022-10-27 10:54 UTC, char0n requested changes
I've suggested change that will make the things work for you again.

2022-10-27 10:54 UTC, char0n commented on packages/apidom-ls/src/config/openapi/responses/completion.ts
>    {
You cannot do this, you need to duplicate every rules. After this change things will work as expected

```s
  {
    label: 'default',
    insertText: 'default',
    ...httpCode3_0CompletionRule,
  } as ApidomCompletionItem,
  {
    label: 'default',
    insertText: 'default',
    ...httpCode3_1CompletionRule,
  } as ApidomCompletionItem,

2022-10-27 20:54 UTC, tim-lai commented
> I've suggested change that will make the things work for you again.

Changes made. I see completion working when under `paths/path-item/operation/responses`, but not `components/responses`.

2022-10-28 08:42 UTC, char0n commented
> > I've suggested change that will make the things work for you again.
> 
> Changes made. I see completion working when under `paths/path-item/operation/responses`, but not `components/responses`.

Here is the type of `Operation Object`.`responses` field

![image](https://user-images.githubusercontent.com/193286/198544189-02f99794-4587-4bf4-a39a-cc7e4469a696.png)

Here is the type of `Components Object`.`responses` field

![image](https://user-images.githubusercontent.com/193286/198544335-28ef1f88-6084-44ad-9e10-ec2641d6f09a.png)

Notice the difference. To say it simply - the `Components Object`.`responses` field if of type of generic map/object instead of `Responses Object`. So what you're seeing is correct and this PR can be merged.

2022-10-28 08:43 UTC, char0n approved these changes
This is now LEGIT.

2022-10-28 08:58 UTC, merged