feat: Add sourceDescription to ns-workflows-1
swagger-api/apidom pull request #3403
Opened 2023-11-16 11:57 UTC by frankkilcommins

Refs: #3392

Add SourceDescription object to apidom-ns-workflows-1

2023-11-16 12:36 UTC, char0n requested changes
Looking good! Some changes needed before the merge

2023-11-16 12:36 UTC, char0n commented on packages/apidom-ns-workflows-1/src/traversal/visitor.ts
> +  isSourceDescriptionElement: ['content'],
```suggestion
  SourceDescriptionElement: ['content'],
```

2023-11-16 12:36 UTC, char0n commented on packages/apidom-ns-workflows-1/src/refractor/visitors/workflows-1/sourceDescription/index.ts
> +import stampit from 'stampit';
Please change the name of the directory from `workflows-1/sourceDescription` to `workflows-1/source-description`. By convention all directories are `dash-cased`.

2023-11-16 12:36 UTC, char0n commented on packages/apidom-ns-workflows-1/src/elements/WorkflowsSpecification1.ts
> +  get sourceDescriptions(): ArrayElement | undefined {
We ca have more specific `NCE` for this list of source description, let's use it.

```suggestion
  get sourceDescriptions(): SourceDescriptionsElement | undefined) {
```

2023-11-16 12:36 UTC, char0n commented on packages/apidom-ns-workflows-1/src/elements/WorkflowsSpecification1.ts
> +  set sourceDescriptions(sourceDescriptions: ArrayElement | undefined) {
We ca have more specific `NCE` for this list of source description, let's use it.

```suggestion
  get sourceDescriptions(): SourceDescriptionsElement | undefined) {
```

2023-11-16 12:36 UTC, char0n commented on packages/apidom-ns-workflows-1/src/refractor/specification.ts
> +            name: FallbackVisitor,
```suggestion
            name: { $ref: '#/visitors/value' },
```

2023-11-16 12:36 UTC, char0n commented on packages/apidom-ns-workflows-1/src/refractor/predicates.ts
> +export const isSourceDescriptionLikeElement = isObjectElement;
We don't need this predicate.
```suggestion
```

2023-11-16 12:36 UTC, char0n commented on packages/apidom-ns-workflows-1/src/refractor/visitors/workflows-1/SourceDescriptionsVisitor.ts
> +      arrayElement.forEach((item: Element) => {
We don't need to assert the shape here. The look can look like this:

```ts
      arrayElement.forEach((item: Element): void => {
        const specPath = ['document', 'objects', 'SourceDescription'];
        const element = this.toRefractedElement(specPath, item);

        this.element.push(element);
      });
```

The reason is that the [SourceDescriptionVisitor](https://github.com/swagger-api/apidom/pull/3403/files#diff-f3530852a6bd15c65b79b08c2a0a74408bad87c3e8ac52c8acd48a65dbdc9538R8) contains `FallbackVisitor` in it's prototype chain and will either refract to semantic `SourceDescription` or generic value.

2023-11-16 12:36 UTC, char0n commented on packages/apidom-ns-workflows-1/src/refractor/visitors/workflows-1/sourceDescription/TypeVisitor.ts
> +      this.element.classes.push('sourceDescription-type');
If you'll use classes here, the convention is to use `dash-case`: 
```suggestion
      this.element.classes.push('source-description-type');
```

2023-11-16 12:38 UTC, char0n commented on packages/apidom-ns-workflows-1/src/index.ts
>  } from './refractor/registration';
`SourceDescriptionsElement` NCE is not exported from here

2023-11-17 11:22 UTC, char0n approved these changes
LGTM. Left [1 comment](https://github.com/swagger-api/apidom/pull/3403#discussion_r1397111759) to possibly look at before the merge.

2023-11-17 11:22 UTC, char0n commented on packages/apidom-ns-workflows-1/src/elements/WorkflowsSpecification1.ts
> +  get sourceDescriptions(): ArrayElement | undefined {
Wasn't it possible to use `SourceDescriptionsElement` here?

2023-11-17 11:24 UTC, char0n commented on packages/apidom-ns-workflows-1/src/elements/WorkflowsSpecification1.ts
> +  get sourceDescriptions(): ArrayElement | undefined {
All right, let's disregard it. Other namespaces are not doing this.

2023-11-17 11:24 UTC, char0n commented on packages/apidom-ns-workflows-1/src/elements/WorkflowsSpecification1.ts
> +  set sourceDescriptions(sourceDescriptions: ArrayElement | undefined) {
All right, let's disregard it. Other namespaces are not doing this.

2023-11-17 14:22 UTC, frankkilcommins commented on packages/apidom-ns-workflows-1/test/predicates.ts
>    InfoElement,
Added the missing test. Thanks for spotting.
FYI - similar tests are missing in OAS3 and 3.1 namespaces for the `isServersElement` predicate

2023-11-20 10:08 UTC, char0n approved these changes
Thank you for the test @frankkilcommins!

2023-11-20 10:16 UTC, merged